# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
